"""Validation report generation.

Per VALIDATION_PLAN_v1.0.md Section 7:
- Each validation run produces JSON + Markdown reports
- Reports must include doc_id, timestamp, status, checks, failures
- Reports are immutable once written
- Reports written to /transfer_station/artifacts/reports/<doc_id>/
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from nexus_core.models.source import ValidationStatus
from nexus_core.validation.checks import CheckResult
from nexus_core.validation.exceptions import ValidationReportError


def generate_json_report(
    doc_id: str,
    run_id: str,
    status: ValidationStatus,
    checks: list[CheckResult],
    validator_version: str = "1.0.0",
) -> dict[str, Any]:
    """Generate machine-readable JSON validation report.

    Per VALIDATION_PLAN_v1.0.md Section 7, reports must include:
    - doc_id
    - validation_timestamp
    - pass_fail status
    - validator_version
    - list of checks performed
    - detailed failure reasons (if any)

    Args:
        doc_id: Document identifier
        run_id: Validation run identifier (UUID)
        status: PASS or FAIL
        checks: List of check results
        validator_version: Version of validator

    Returns:
        Dictionary representing JSON report structure
    """
    # Extract failure reasons
    failure_reasons = []
    for check in checks:
        if not check.passed:
            failure_reasons.append(
                f"{check.check_name}: {check.message}"
            )

    report = {
        "doc_id": doc_id,
        "run_id": run_id,
        "validation_timestamp": datetime.utcnow().isoformat() + "Z",
        "status": status.value,
        "validator_version": validator_version,
        "checks_performed": [
            {
                "check_name": check.check_name,
                "passed": check.passed,
                "message": check.message,
                "details": check.details,
            }
            for check in checks
        ],
        "failure_reasons": failure_reasons,
        "summary": {
            "total_checks": len(checks),
            "passed_checks": sum(1 for check in checks if check.passed),
            "failed_checks": sum(1 for check in checks if not check.passed),
        },
    }

    return report


def generate_markdown_report(
    doc_id: str,
    run_id: str,
    status: ValidationStatus,
    checks: list[CheckResult],
    validator_version: str = "1.0.0",
) -> str:
    """Generate human-readable Markdown validation report.

    Args:
        doc_id: Document identifier
        run_id: Validation run identifier (UUID)
        status: PASS or FAIL
        checks: List of check results
        validator_version: Version of validator

    Returns:
        Markdown-formatted report as string
    """
    timestamp = datetime.utcnow().isoformat() + "Z"
    status_emoji = "✅" if status == ValidationStatus.PASS else "❌"

    lines = [
        f"# Validation Report {status_emoji}",
        "",
        f"**Document ID:** `{doc_id}`",
        f"**Run ID:** `{run_id}`",
        f"**Timestamp:** {timestamp}",
        f"**Status:** **{status.value}**",
        f"**Validator Version:** {validator_version}",
        "",
        "---",
        "",
    ]

    # Summary
    passed_count = sum(1 for check in checks if check.passed)
    failed_count = sum(1 for check in checks if not check.passed)

    lines.extend([
        "## Summary",
        "",
        f"- **Total Checks:** {len(checks)}",
        f"- **Passed:** {passed_count}",
        f"- **Failed:** {failed_count}",
        "",
        "---",
        "",
    ])

    # Checks performed
    lines.extend([
        "## Checks Performed",
        "",
    ])

    for i, check in enumerate(checks, start=1):
        check_emoji = "✅" if check.passed else "❌"
        lines.extend([
            f"### {i}. {check.check_name} {check_emoji}",
            "",
            f"**Status:** {' PASS' if check.passed else 'FAIL'}",
            f"**Message:** {check.message}",
            "",
        ])

        # Add details if failed
        if not check.passed and check.details:
            lines.append("**Details:**")
            lines.append("```json")
            lines.append(json.dumps(check.details, indent=2))
            lines.append("```")
            lines.append("")

    # Failure reasons summary (if any)
    if failed_count > 0:
        lines.extend([
            "---",
            "",
            "## Failure Reasons",
            "",
        ])
        for check in checks:
            if not check.passed:
                lines.append(f"- **{check.check_name}:** {check.message}")
        lines.append("")

    # Footer
    lines.extend([
        "---",
        "",
        f"*Report generated by Nexus Core Validation Agent v{validator_version}*",
        "",
        "Per VALIDATION_PLAN_v1.0.md and INGESTION_VALIDATION_AGENT_PROMPT_v1.0.md",
    ])

    return "\n".join(lines)


def write_reports(
    reports_dir: Path,
    doc_id: str,
    run_id: str,
    json_content: dict[str, Any],
    md_content: str,
) -> tuple[Path, Path]:
    """Write validation reports to disk.

    Per VALIDATION_PLAN_v1.0.md Section 7:
    - Reports written to /transfer_station/artifacts/reports/<doc_id>/
    - File names: validation_<run_id>.json and validation_<run_id>.md
    - Reports are immutable once written

    Args:
        reports_dir: Base reports directory path
        doc_id: Document identifier
        run_id: Validation run identifier
        json_content: JSON report content
        md_content: Markdown report content

    Returns:
        Tuple of (json_path, md_path) for written reports

    Raises:
        ValidationReportError: If report writing fails
    """
    try:
        # Create doc_id subdirectory if it doesn't exist
        doc_reports_dir = reports_dir / doc_id
        doc_reports_dir.mkdir(parents=True, exist_ok=True)

        # Define file paths
        json_path = doc_reports_dir / f"validation_{run_id}.json"
        md_path = doc_reports_dir / f"validation_{run_id}.md"

        # Write JSON report
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(json_content, f, indent=2, ensure_ascii=False)

        # Write Markdown report
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        return (json_path, md_path)

    except Exception as e:
        raise ValidationReportError(
            message=f"Failed to write validation reports: {str(e)}",
            details={
                "doc_id": doc_id,
                "run_id": run_id,
                "reports_dir": str(reports_dir),
                "error": str(e),
            },
        ) from e


def get_latest_report(reports_dir: Path, doc_id: str) -> Path | None:
    """Get path to most recent validation report for a doc_id.

    Args:
        reports_dir: Base reports directory path
        doc_id: Document identifier

    Returns:
        Path to latest JSON report, or None if no reports exist
    """
    doc_reports_dir = reports_dir / doc_id
    if not doc_reports_dir.exists():
        return None

    # Find all validation JSON files
    json_files = list(doc_reports_dir.glob("validation_*.json"))
    if not json_files:
        return None

    # Return most recently modified
    return max(json_files, key=lambda p: p.stat().st_mtime)
